/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/7.0.79
 * Generated at: 2017-08-02 16:12:37 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.WEB_002dINF.jsp;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;
import com.jaeksoft.searchlib.renderer.Renderer;
import com.jaeksoft.searchlib.renderer.plugin.AuthPluginInterface;

public final class renderer_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
        throws java.io.IOException, javax.servlet.ServletException {

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("<!DOCTYPE html PUBLIC \"-//W3C//DTD XHTML 1.0 Transitional//EN\" \"http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd\">\n");
      out.write(" \n");
      out.write("\n");
      out.write("\n");

	Renderer renderer = (Renderer) request.getAttribute("renderer");
	AuthPluginInterface.User user = (AuthPluginInterface.User) session.getAttribute("rendererUser");
	String login = user == null ? "" : user.username;

      out.write("\n");
      out.write("<html xmlns=\"http://www.w3.org/1999/xhtml\">\n");
      out.write("<head>\n");
      out.write("<meta http-equiv=\"Content-type\" content=\"text/html; charset=UTF-8\" />\n");
      out.write("<style type=\"text/css\">\n");
      out.write("body,html {\n");
      out.write("\tmargin: 0;\n");
      out.write("\tpadding: 0;\n");
      out.write("}\n");
      out.write("#oss-main {\n");
      out.write("\tmargin-left: ");
      out.print(renderer.getFacetWidth());
      out.write(";\n");
      out.write("}\n");
      out.write("#oss-facet {\n");
      out.write("\tfloat: left;\n");
      out.write("\twidth: ");
      out.print(renderer.getFacetWidth());
      out.write(";\n");
      out.write("}\n");
      out.write("#oss-header {\n");
      out.write("\twidth: 100%;\n");
      out.write("}\n");
      out.write("#oss-footer {\n");
      out.write("\twidth: 100%;\n");
      out.write("\tclear: both;\n");
      out.write("}\n");
      out.write("#oss-wrap {\n");
      out.write("\twidth: 100%;\n");
      out.write("\tmargin:0 auto;\n");
      out.write("\tmin-width: 700px;\n");
      out.write("}\n");
      out.print(renderer.getCss());
      out.write("\n");
      out.write("</style>\n");
      out.write("<title>OpenSearchServer</title>\n");
      out.write("<script type=\"text/javascript\" src=\"js/opensearchserver.js\" charset=\"UTF-8\"></script>\n");
      out.write("</head>\n");
      out.write("<body>\n");
      out.write("\t<div id=\"oss-wrap\">\n");
      out.write("\t\t<div id=\"oss-header\">\n");
      out.write("\t\t\t");
      out.print(renderer.getHeader());
      out.write("\n");
      out.write("\t\t</div>\n");
      out.write("\t\t");
 if (renderer.isAuthentication()) { 
      out.write("\n");
      out.write("\t\t<div id=\"oss-login\">\n");
      out.write("\t\t");
      out.print(login);
      out.write('\n');
      out.write('	');
      out.write('	');
 if (renderer.isLogout()){ 
      out.write("\n");
      out.write("\t\t&nbsp;-&nbsp;<a href=\"");
      out.print(request.getAttribute("getUrl"));
      out.write("&logout\">");
      out.print(renderer.getLogoutText());
      out.write("</a>\n");
      out.write("\t\t");
 } 
      out.write("\n");
      out.write("\t\t</div>\n");
      out.write("\t\t");
 } 
      out.write("\n");
      out.write("\t\t<div id=\"oss-facet\">\n");
      out.write("\t\t\t\t");
      org.apache.jasper.runtime.JspRuntimeLibrary.include(request, response, "renderer/facet.jsp", out, false);
      out.write("\n");
      out.write("\t\t\t\t</div>\n");
      out.write("\t\t\t<div id=\"oss-main\">\n");
      out.write("\t\t\t");
      org.apache.jasper.runtime.JspRuntimeLibrary.include(request, response, "renderer/form.jsp", out, false);
      out.write("\n");
      out.write("\t\t\t");
      org.apache.jasper.runtime.JspRuntimeLibrary.include(request, response, "renderer/numfound.jsp", out, false);
      out.write("\n");
      out.write("\t\t\t");
      org.apache.jasper.runtime.JspRuntimeLibrary.include(request, response, "renderer/doclist.jsp", out, false);
      out.write("\n");
      out.write("\t\t\t</div>\n");
      out.write("\t\t<div id=\"oss-footer\">\n");
      out.write("\t\t\t");
      out.print(renderer.getFooter());
      out.write("\n");
      out.write("\t\t</div>\n");
      out.write("\t\t<div align=\"right\" style=\"clear:both;\">\n");
      out.write("\t\t\t<a href=\"http://www.open-search-server.com/\" target=\"_blank\"><img\n");
      out.write("\t\t\t\talt=\"OpenSearchServer Logo\" src=\" images/oss_logo_32.png\"\n");
      out.write("\t\t\t\tstyle=\"vertical-align: bottom\" /></a>\n");
      out.write("\t\t</div>\n");
      out.write("\t</div>\n");
      out.write("</body>\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
